### ISSUE TITLE
Due Sat 12/8/18: Milestone 1 - Project Specification

### ISSUE THREAD

**Issue by manananggal** [houblon/paymates#12]
- [x] Project group name. Staff names.
- [x] Software goal and concept: Explain in terms of one or more “user stories” of the problem you’re
software is attempting to solve.
- [x] Submit the project specifications. Which APIs or data it will be using, and broadly
what work you expect might be involved. 
- [x] Include some cursory wireframing: You don’t have to wireframe every single feature or screen, but at least get the core ones down, just to ensure everyone in your group is broadly on the same page visually.
- [x] Challenges and unknowns: Factor in problems you may encounter, given the limited time available
and what your team has so far learned of web development. For potential “show-stoppers”, include
contingency plans.
- [x] Group roles: Roughly outline the roles of each group member. Example responsibilities include frontend engineer / design, back-end engineer, and API & data engineer. It’s okay if you don’t follow 100% one role or another, or mix it up.

**Comment by houblon** [comment]
Group name: Paymates
Staff names: 
- jbot
- manananggal
- houblon
Project specs:
- API / data: mLab database
- work involved: calculate financial balances using a data model and React (all aspects of CRUD)
Wireframing: in progress
Challenges and unknowns: data model definition
Group roles:
- jbot: Minister of Propaganda (back-end engineer & scrum master)
- manananggal: Secretary of State (frontend engineer / design)
- houblon: gnome (API & data engineer)

**Comment by manananggal** [comment]
![screen shot 2018-12-08 at 1 24 44 am](https://user-images.githubusercontent.com/41496184/49684450-f18f5980-fa88-11e8-87d2-180b61d8ced2.png)
This fulfills both issues: Landing Page #6 and Household report #7.

**Comment by manananggal** [comment]
User cases

1. Household: Monthly accounting among roommates. Some bills are in Alice's name. Some bills are in Bob's name. Candice pays for groceries. A rolling accounting of regularly occurring monthly transactions. Could work for move-ins, move-outs; and could be adjusted for couples occupying one room.

2. Restaurant bill among friends, not in a household: 
a) Alice paid on her card. Bob only ordered appetizers. Candice paid for extra drinks.
b) If they regularly meet, can possibly be a rolling accounting.

3. Single Trip Event: Friends take a Tahoe trip together
	
a) Alice paid for accommodations; 
b) Bob paid for the food;
c) Candice paid for the lift tickets;
d) David paid for gas and miscellaneous incidentals.

Single-line edit-ability.
No sign-ins, sign-ups. Simple interface. Peace among friends who always settle up.

**Comment by manananggal** [comment]
COMPONENTIZATION OF APP

Home/Household-Group-Event Page
Group Member Input Section
1) Input/Placeholder field: "New Household/Group/Even Description"
2) Alert: "You must rename "NEW HOUSE/GROUP/EVENT DESCRIPTION" (if not different text)
3) Input/Placeholder field: "Group Member Name 1"
4) Alert: "You must create at least two Group Members (if not different text)
5) Button: "+ ADD name" (creates another "Group Member Name" field)
6) Button: "- REMOVE name" (deletes incorrect "Group Member Name" field, contents and all)


Line Item Input Section
1) mm/dd/yy drop-down input under "MM/DD/YY:" column.
2) Character Text Input: under "Vendor/Utility Name:" column (once entered, becomes part of drop-down menu, assuming ongoing monthly recurring accounting).
3) Accounting Input under "Amount Paid:" column (Currency at this time assumes USD$).
4) Stored Group Member Name Dropdown under "Paid by:" column.
5) Button: "+ ADD item" (next to last line item) to input an additional line item.
6) Button: "DONE" (Writes to DB)

Summary of Transactions by Group Section
1) "+ EDIT -" button next to each rendered line item to manually adjust percentages or delete entire line for proper re-entry.

**Comment by manananggal** [comment]
Challenges and unknowns:
1. How long each component/function will take to successfully MERN-ify.
2. Discerning the order of the most important components/functions to create for MVP for the sake of time.

**Comment by manananggal** [comment]
Submitted via Mattermost to MB.
