### ISSUE TITLE
Due Mon 12/10/18: Milestone 2 - Templates, wireframes, proof-of-concepts

### ISSUE THREAD

**Issue by manananggal** [houblon/paymates#13]
- [ ] Screenshots of your wireframes and static pages
- [ ] GitHub organization for your group
- [ ] Ideally: Proof of concept of core data, API, or backend concepts
-------
1. **HTML & CSS “Click-through” template of core concept:**
Click-through template: The next milestone involves fleshing out your idea by building out wireframes and static HTML & CSS templates. Focus on styling, so include only dummy data at this stage. Feel free to leverage code you find online, but note that by the end, you should try to heavily customized any starter template code to the point that it is not immediately obvious where it came from.
2. **Full wireframes of all screens**
Full wireframes: Try to thoroughly plan out every page and aspect of your application at this point,
possibly cutting down features until you have 1 or 2 core features you build the project around.
3. **Proof of concepts for core data, API, core view logic**
API & data proof-of-concepts: Those working on API and back-end code should start work on basic
proof-of-concepts. Build a script that fetches the exact data you need from the API, either as a CLI script or a little server based on an activity or sample project.
