### ISSUE TITLE
Due 12/22/18: Milestone 4 - Presentation of app at conference

### ISSUE THREAD

**Issue by manananggal** [houblon/paymates#15]
- [ ] Create Google Slides for PayMates
- [ ] User stories (gist of the the problem we are trying to solve)
        - [ ] User story 1: Household split
        - [ ]User story 2: Restaurant split
- [ ] Jesse's spiel: Intro and premise for App
- [ ] Steve's spiel: technical challenges overcame
- [ ] Maria's spiel: live demo of the site
