### ISSUE TITLE
Open date: Milestone 5 - Portfolio

### ISSUE THREAD

**Issue by manananggal** [houblon/paymates#18]
- [ ] Flesh out README.md with full description
- [ ] Buy domain, and/or spend more time on logo and branding
- [ ] Add to resume
- [ ] Add any additional stand-out features and generally polish the project
- [ ] Add a logo and description to your organization.
